
server:
  port: 9090

#Below part is not required.

zuul:
  routes:
    rws:
      path: /rwsMetaData
      url: ${rws.url}
    customer:
      path: /customer/**
      url: http://localhost:8081/customer

  