
server:
  port: 8082

#Below part is not required.

zuul:
  routes:
    rws:
      path: /rws/**
      url: ${rws.url:http://localhost:8100}
    customer:
      path: /customer/**
      url: http://localhost:8081/customer

clientIdSecret:
  test: test
  clientId1: clientSecret1

  
